### ISSUE TITLE
Занятие 1 и 2.

### ISSUE THREAD

**Issue by stsdmchv** [anasta-ziii/Borovkova#1]
Нет строки кодировки.
Отсутствуют скриншоты к решениям.
Проверь номера задач для занятия 2. Одна задача отсутствует.

**Comment by anasta-ziii** [comment]
Здравствуйте! 
Я переделала все. Добавила строку кодировки, прикрепила к каждой задаче скрин и довабила еще одну программу во 2ой урок. 
Проверьте, пожалуйста!
